language: python

env:
  -export DATABASE_URL='postgresql://postgres:postgres@localhost/fastfoodfast'
  -export FLASK_ENV='development'

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

services:
  -postgresql

addon:
  -postgresql: "9.6"

before_script:
  # -psql -c 'CREATE DATABASE fastfoodfast' -u postgres
  # -psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA'

script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
